---
title: "map"
output: html_document
---

```{r}
setwd("~/Documents/VIZ_SPRING/data_viz_project_spring")

library(tidyverse)
library(ggplot2)
library(lubridate)
library(dplyr)
library(stringr)
library(sf)
library(plotly)
library(leaflet)
library(mapview)
library(gganimate)
library(gifski)
library(paletteer)
library(ggthemes)

df = read_csv("Xerces Site Counts by County.csv", n_max = 387)
site_locations = read_csv("sites.csv", 
                          col_select = c("SiteID","Site Name",
                                         "Latitude","Longitude"))

df_long = pivot_longer(df, 
                       cols = !c('SITE ID','SITE NAME','COUNTY or REGION'),
                       names_to = 'time_period',
                       values_to = 'count') %>% 
          mutate(
                season = case_when(
                    str_starts(time_period, "ES") ~ "Early Season",
                    str_starts(time_period, "LS") ~ "Late Season",
                    TRUE ~ "Peak Season"),
                year = as.numeric(str_match(time_period, "[0-9]{4}")))

# join lat and longs to site IDs
df_long = left_join(df_long, site_locations, by=c("SITE ID" = "SiteID"))

# only observations at peak season
df_peak = df_long %>% filter(season == "Peak Season")

# all observations, including late and early season
# ESday = round(yday("2023-10-31")/365, 3)
# Xday = round(yday("2023-11-25")/365, 3)
# LSday = round(yday("2023-12-31")/365, 3)
# 
# df_all_dates = df_long %>%
#     mutate(date = case_when(
#         str_starts(time_period, "ES") ~ year + ESday,
#         str_starts(time_period, "LS") ~ year + LSday,
#         TRUE ~ year + Xday
#     ))

head(df_peak)
```

```{r}
# map just the site locations
site_locations = drop_na(site_locations)

mapview(site_locations, xcol='Longitude', ycol='Latitude',
        crs=4269, grid = FALSE)
```

```{r}
# map site locations with size of points representing butterfly count
# just 1997
df_year = df_peak %>% filter(year == 1997)

CA = map_data('state', 'california')

p = ggplot(data=df_year, aes(x=Longitude, y=Latitude)) +
    geom_polygon(data=CA, 
                 aes(x=long, y=lat, group=group),
                 fill='lightblue') +
    geom_path(data=CA, 
                 aes(x=long, y=lat, group=group),
                 color='lightblue4') +
    coord_map() +
    geom_point(alpha=0.5, aes(size=count, color=count)) +
    scale_color_gradientn(colors=paletteer_c("ggthemes::Red-Gold", 30) ) +
    theme_void() 
```

```{r}
# https://r-graph-gallery.com/package/gganimate.html

CA = map_data('state', 'california')

# animated gif
p = ggplot(data=df_peak, aes(x=Longitude, y=Latitude)) +
    geom_polygon(data=CA, 
                 aes(x=long, y=lat, group=group),
                 fill='lightblue') +
    geom_path(data=CA, 
                 aes(x=long, y=lat, group=group),
                 color='lightblue4') +
    coord_map() +
    geom_point(alpha=0.5, aes(size=count, color=count)) +
    scale_color_gradientn(colors=paletteer_c("ggthemes::Red-Gold", 30) ) +
    theme_void()  +
    ggtitle("Year: {frame_time}") +
    transition_time(year) +
    ease_aes("linear") +
    enter_fade() +
    exit_fade()

# animate(p, nframes = 28, fps = 2, width = 400, height = 600,
#         # start_pause = 10, end_pause = 10,
#         renderer = gifski_renderer())

anim_save(animation = p, "map.gif")
```

